---

- hosts: localhost
  tasks:
    - name: Install needed packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - pcre
        - pcre-devel

    - name: download nginx source code
      get_url:
        dest: "/var/tmp"
        url: "https://nginx.org/download/nginx-1.8.1.tar.gz"

    - name: tar nginx source code
      shell: >
        tar zxf /var/tmp/nginx-1.8.1.tar.gz -C /var/tmp
