---
- name: Install needed packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - pcre
    - pcre-devel
    - openssl
    - openssl-devel

- name: add nginx repository
  template:
    dest: /etc/yum.repos.d/nginx.repo 
    src: nginx.repo.j2

- name: install nginx
  yum: 
    name: nginx
    state: latest
